name: House Scraper

on:
  schedule:
    # Spustí se každou hodinu (0 minut každé hodiny)
    - cron: '0 * * * *'
  
  # Umožní manuální spuštění z GitHub UI
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser chromium-chromedriver
      - name: Setup Chrome driver
        run: |
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          chromedriver --version
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Run the scraping script
        run: python main.py
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-update from scraping script"
          git push