name: House Scraper

on:
  schedule:
    # Spustí se každou hodinu (0 minut každé hodiny)
    - cron: '0 * * * *'
  
  # Umožní manuální spuštění z GitHub UI
  workflow_dispatch:

jobs:
  scrape-houses:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4
        
    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install firefox-esr
        
        # Stáhnout nejnovější geckodriver
        GECKODRIVER_VERSION=$(curl -s "https://api.github.com/repos/mozilla/geckodriver/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver
        
    - name: Run house scraper
      run: |
        cd ${{ github.workspace }}
        python main.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add seen.json
        git diff --staged --quiet || git commit -m "Update seen listings - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
