name: House Scraper

on:
  schedule:
    - cron: '0 * * * *'
  
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Firefox
        run: |
         sudo rm -rf /usr/local/bin/geckodriver
         wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
         tar -xvzf geckodriver*
         chmod +x geckodriver
         sudo mv geckodriver /usr/local/bin/

      - name: Install Selenium and BeautifulSoup
        run: |
          pip install selenium==4.16.0
          pip install beautifulsoup4
          pip install requests

      - name: Build
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Commit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_MSG: |
            SCRAPE: scraped Data
        run: |
          rm -rf geckodriver*
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git pull origin ${GITHUB_REF}
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})